### PR TITLE
Fix typo in README

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by stevepeak** [comment]
Thanks!

**Comment by blueyed** [comment]
@stevepeak 
Thanks for merging.

I've wondered about the Github integration of codecov.
Is it possible to have a check failure if changes from a PR are not covered by X %?
Or are the codecov checks limited to failures, in case the build failed altogether (https://github.com/tomchristie/django-rest-framework/pull/3394)?

What is the best-practice of handling builds from Travis matrix?  Should it be uploaded only once, or for each combination of Python/Django/...?

**Comment by stevepeak** [comment]
> Check failure if changes from a PR are not covered by X %?

We do have a Github Status that does this check. A project (the entire project coverage) and a patch (the lines adjusted) coverage statuses. We have a ticket to add thresholds to them here: https://github.com/codecov/support/issues/88

> codecov checks limited to failures

To insure accuracy of reporting Codecov, as of now, requires the CI state to be successful to compare coverage. If tests fail then some lines may not be hit and therefore cause coverage to decrease (very common). I you have suggestions on changing this feature please let me know how :)

> best-practice of handling builds from Travis matrix 

Codecov merges reports automatically, no setup required. The only specification you can optionally add is `-e ENV_NAME` to distinguish builds [for example](https://codecov.io/gh/pyca/cryptography?ref=f5382255cff396aadc4466565acebd4b57b8deb0&build=7163.1)

**Comment by blueyed** [comment]
@stevepeak 
Thanks for your answers!

> We do have a Github Status that does this check. A project (the entire project coverage) and a patch (the lines adjusted) coverage statuses.

They are not enabled for this repo though, are they? (#7)

**Comment by stevepeak** [comment]
Your very welcome :+1: 

You can see the two statuses in the commits above. Codecov has not got an upload from the pending build yet.

**Pull request merged**
