### PR TITLE
Readme update

### PR DESCRIPTION
**Pull request by TomPed**
Updated the README to follow standards. Are the any language specific caveats that need to be added?

### CODE REVIEW

**Comment by stevepeak** [comment]
Cobertura reports can expire. It's important that customers are aware that Codecov will reject reports that are older than 12 hours.
Our logs should contain details if a report expired.

**Comment by TomPed** [comment]
@stevepeak I accidentally deleted my forked repo. Do you think you can fix the conflict. (the `README.rst` should be deleted). Thanks!

**Comment by thomasrockhu** [comment]
Hi @TomPed, this PR is a little bit outdated now, but I wanted to make sure we pull in anything that should be in the current `README`.  I know this was opened over a year ago, but let me know or if this should be closed

**Comment by thomasrockhu** [comment]
Closing in favor of https://github.com/codecov/example-python/pull/52

**Pull request closed without merging**
